### ISSUE TITLE
"ReferenceError: TextEncoder is not defined" when `npm test` on a Create-React-App

### ISSUE THREAD

**Issue by danielbakas** [inrupt/solid-ui-react#749]
### Search terms you've used

* TextEncoder

### Bug description

Running `npm test` results in the a TextEncoder error.

### To Reproduce
1. Create a new Create-React-App
2. Install dependencies
3. Run `npm test`

### Expected result

* Succesful test

### Actual result

```zsh
 FAIL  src/components/App/index.test.js
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      13 | //* Imports
      14 | // Package Imports
    > 15 | import { useSession } from "@inrupt/solid-ui-react";
         | ^
      16 | import { Image, Nav, Navbar } from "react-bootstrap";
      17 | import { Link, NavLink } from "react-router-dom";
      18 | // Project Imports

      at Object.<anonymous> (node_modules/jose/dist/node/cjs/lib/buffer_utils.js:5:23)
      at Object.<anonymous> (node_modules/jose/dist/node/cjs/runtime/base64url.js:5:27)
      at Object.<anonymous> (node_modules/jose/dist/node/cjs/jwe/flattened/decrypt.js:4:24)
      at Object.<anonymous> (node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js:4:22)
      at Object.<anonymous> (node_modules/jose/dist/node/cjs/index.js:4:20)
      at Object.<anonymous> (node_modules/@inrupt/solid-client-authn-core/dist/index.js:4:12)
      at Object.<anonymous> (node_modules/@inrupt/solid-client-authn-browser/src/Session.ts:26:1)
      at Object.<anonymous> (node_modules/@inrupt/solid-client-authn-browser/src/index.ts:22:1)
      at webpackUniversalModuleDefinition (node_modules/@inrupt/solid-ui-react/dist/webpack:/@inrupt/solid-ui-react/webpack/universalModuleDefinition:3:1)
      at Object.<anonymous> (node_modules/@inrupt/solid-ui-react/dist/webpack:/@inrupt/solid-ui-react/webpack/universalModuleDefinition:10:2)
      at Object.<anonymous> (src/components/Page/content/NavBar/index.jsx:15:1)
      at Object.<anonymous> (src/components/Page/content/Header/index.jsx:21:1)
      at Object.<anonymous> (src/components/Page/index.jsx:16:1)
      at Object.<anonymous> (src/components/Router/index.jsx:17:1)
      at Object.<anonymous> (src/components/App/index.jsx:17:1)
      at Object.<anonymous> (src/components/App/index.test.js:14:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.745 s
Ran all test suites related to changed files.
```

### Environment
```zsh
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 177.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Documents/Profesional/Semantyk/Projects/Semantyk/client/node_modules/.bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Safari: 16.2
  npmPackages:
    @comunica/query-sparql-solid: ^2.3.0 => 2.4.0 
    @inrupt/solid-client: ^1.23.3 => 1.25.2 
    @inrupt/solid-ui-react: ^2.8.2 => 2.8.2 
    @inrupt/vocab-common-rdf: ^1.0.5 => 1.0.5 
    @react-three/drei: ^9.40.0 => 9.56.24 
    @react-three/fiber: ^8.9.1 => 8.11.1 
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    bootstrap: ^5.2.2 => 5.2.3 
    lamina: ^1.1.23 => 1.1.23 
    node-fetch: ^3.2.10 => 3.3.0 
    npm: ^8.19.3 => 8.19.4 
    rdflib: ^2.2.20 => 2.2.26 
    react: ^18.2.0 => 18.2.0 
    react-bootstrap: ^2.5.0 => 2.7.2 
    react-dom: ^18.2.0 => 18.2.0 
    react-force-graph: ^1.41.15 => 1.42.0 
    react-helmet-async: ^1.3.0 => 1.3.0 
    react-router-dom: ^6.4.3 => 6.8.1 
    react-scripts: 5.0.1 => 5.0.1 
    react-sizeme: ^3.0.2 => 3.0.2 
    serve: ^14.2.0 => 14.2.0 
    stream-to-string: ^1.2.0 => 1.2.1 
    three: ^0.146.0 => 0.146.0 
    three-forcegraph: ^1.39.7 => 1.41.4 
    url: ^0.11.0 => 0.11.0 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @solid/community-server: 5.1.0
    corepack: 0.15.1
    npm: 8.19.3
```

**Comment by danielbakas** [comment]
Hi there! Any updates on this? Still having the issue. I tried with `node v14` and tried reduced my deps to these, but still not working:

```json
  "dependencies": {
    "@inrupt/solid-client": "^1.29.0",
    "@inrupt/solid-ui-react": "^2.8.2",
    "@react-three/fiber": "^8.13.4",
    "@testing-library/react": "^14.0.0",
    "bootstrap": "^5.3.0",
    "rdflib": "^2.2.32",
    "react": "^18.2.0",
    "react-bootstrap": "^2.8.0",
    "react-dom": "^18.2.0",
    "react-force-graph": "^1.43.0",
    "react-helmet-async": "^1.3.0",
    "react-router-dom": "^6.14.1",
    "three": "^0.154.0",
    "url": "^0.11.1"
  },
  "devDependencies": {
    "depcheck": "^1.4.3",
    "react-scripts": "^5.0.1"
  },
```

Thanks! Looking forward to your answer

**Comment by jeswr** [comment]
The `TextEncoder` class is globally available in the browser; but appears not to be available in your testing environment.

This is a [known issue](https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest) in the jest JSdom environment; and we use [this polyfill](https://github.com/inrupt/typescript-sdk-tools/blob/b3a340654ad370d676f72e17a21bc1238c968ba5/packages/jest-jsdom-polyfills/index.js#L32) to make it globally available before running our jsdom tests ([this is how we set it up in solid-client-js](https://github.com/inrupt/solid-client-js/blob/main/jest.setup.ts)).

At a cursory glance `create-react-app` appears to use the same jsdom environment in which case the solution for you would be to polyfill the `TextEncoder` in your testing environment.

**Comment by danielbakas** [comment]
Thanks @jeswr. Adding these did the trick:

```js
import { TextDecoder, TextEncoder } from "text-encoding";
global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```
Now I have a different issue, unrelated to Solid.

Cheers!
